# Site settings
title: brunojensen
header-img: img/home-bg.jpg
email: ordead6@gmail.com
copyright_name: brunojensen
description: "knowledge only real when shared"
baseurl: ""
url: "http://brunojensen.github.io"
github_username:  brunojensen
linkedin_username:  brunojensen
medium_username: brunojensen
show_profile_link: true
#email_username:  ordead6@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
